/////////////////////////////////////////////////////////////////////////////////////////////////
//Jacob Jurecki
//hw04
//PokerHandCheck
//
/////
/////
import java.lang.Math; 
import java.util.Random;
//importing math and random 
public class PokerHandCheck {
    //main method required for every Java program
    public static void main(String[] args)  {
        //
        //(below)using int's and random number generator suit type
        
        int cardOneType = (int)(Math.random()*(4))+1;
        int cardTwoType = (int)(Math.random()*(4))+1;
        int cardThreeType = (int)(Math.random()*(4))+1;
        int cardFourType = (int)(Math.random()*(4))+1;
        int cardFiveType = (int)(Math.random()*(4))+1;
        
        //(below)using a string for card values along with five separate random selections
        // of values in that string. Least complicated method in my opinion.
        //the label of the string is "cardOneValue" but its really the card value for
        //every card in the had. after all of this coding I truly did not feel like
        //going back and changing the name of it.
        //hopefully my grader will understand.
        
        String[] cardOneValue = {"Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten","Jack","King","Ace"};
        Random random = new Random();
        int selectOne = random.nextInt(cardOneValue.length);
        
        
        int selectTwo = random.nextInt(cardOneValue.length);
        
        
        
        int selectThree = random.nextInt(cardOneValue.length);
       
        
        
        int selectFour = random.nextInt(cardOneValue.length);
        
        
       
        int selectFive = random.nextInt(cardOneValue.length);
        
        
        //(below)labeling each number generated by the randome number generator 
        //with a suit for each of the five string values from the random string selection 
        //and printing it along with each randomly selected string value from the
        //string that were selected in the lines just above these
        //
        //CARD ONE
        if (cardOneType==1)
        System.out.println(cardOneValue[selectOne]+" of Spades");
        else if (cardOneType==2)
        System.out.println(cardOneValue[selectOne]+" of Hearts");
        else if (cardOneType==3)
        System.out.println(cardOneValue[selectOne]+" of Diamonds");
        else if (cardOneType==4)
        System.out.println(cardOneValue[selectOne]+" of Clubs"); 
        else
        System.out.println("error");
        //CARD TWO
        if (cardTwoType==1)
        System.out.println(cardOneValue[selectTwo]+" of Spades");
        else if (cardTwoType==2)
        System.out.println(cardOneValue[selectTwo]+" of Hearts");
        else if (cardTwoType==3)
        System.out.println(cardOneValue[selectTwo]+" of Diamonds");
        else if (cardTwoType==4)
        System.out.println(cardOneValue[selectTwo]+" of Clubs"); 
        else
        System.out.println("error");
        //CARD THREE
        if (cardThreeType==1)
        System.out.println(cardOneValue[selectThree]+" of Spades");
        else if (cardThreeType==2)
        System.out.println(cardOneValue[selectThree]+" of Hearts");
        else if (cardThreeType==3)
        System.out.println(cardOneValue[selectThree]+" of Diamonds");
        else if (cardThreeType==4)
        System.out.println(cardOneValue[selectThree]+" of Clubs"); 
        else
        System.out.println("error");
        //CARD FOUR
        if (cardFourType==1)
        System.out.println(cardOneValue[selectFour]+" of Spades");
        else if (cardFourType==2)
        System.out.println(cardOneValue[selectFour]+" of Hearts");
        else if (cardFourType==3)
        System.out.println(cardOneValue[selectFour]+" of Diamonds");
        else if (cardFourType==4)
        System.out.println(cardOneValue[selectFour]+" of Clubs"); 
        else
        System.out.println("error");
        //CARD FIVE
         if (cardFiveType==1)
        System.out.println(cardOneValue[selectFive]+" of Spades");
        else if (cardFiveType==2)
        System.out.println(cardOneValue[selectFive]+" of Hearts");
        else if (cardFiveType==3)
        System.out.println(cardOneValue[selectFive]+" of Diamonds");
        else if (cardFiveType==4)
        System.out.println(cardOneValue[selectFive]+" of Clubs"); 
        else
        System.out.println("error");
        
        
        
        //(below) identifying if there is three of a kind within the cards selected without using a loop as requested
        //by listing all of the possible 3 of a kind matches. 
        //there is probably a more effective way of doing this except I just could not find one that used randomly 
        //selected string values as opposed to randomly generated numbers
        if (selectOne==selectFour&&selectOne==selectFive||selectOne==selectFour&&selectOne==selectThree||selectOne==selectFour&&selectOne==selectTwo
        ||selectOne==selectFive&&selectOne==selectThree||selectOne==selectFive&&selectOne==selectTwo||selectOne==selectTwo&&selectOne==selectThree
        
        ||selectTwo==selectThree&&selectTwo==selectFour||selectTwo==selectThree&&selectTwo==selectFive||selectTwo==selectThree&&selectTwo==selectOne
        ||selectTwo==selectFour&&selectTwo==selectFive||selectTwo==selectFour&&selectTwo==selectOne||selectTwo==selectFive&&selectTwo==selectOne
        
        ||selectThree==selectOne&&selectThree==selectTwo||selectThree==selectOne&&selectThree==selectFour||selectThree==selectOne&&selectThree==selectFive
        ||selectThree==selectTwo&&selectThree==selectFour||selectThree==selectTwo&&selectThree==selectFive||selectThree==selectFour&&selectThree==selectFive
        
        ||selectFour==selectOne&&selectFour==selectTwo||selectFour==selectOne&&selectFour==selectThree||selectFour==selectOne&&selectFour==selectFive
        ||selectFour==selectTwo&&selectFour==selectThree||selectFour==selectTwo&&selectFour==selectFive||selectFour==selectThree&&selectFour==selectFive
        
        ||selectFive==selectOne&&selectFive==selectTwo||selectFive==selectOne&&selectFive==selectThree||selectFive==selectOne&&selectFive==selectFour
        ||selectFive==selectTwo&&selectFive==selectThree||selectFive==selectTwo&&selectFive==selectFour||selectFive==selectThree&&selectFive==selectFour)
        
        System.out.println("You have 3 of a kind!");
        //(below) identifying if there is a 2 pair using the same lenthy method as for 3 of a kind.
        //there is 3 of a kind matches listed within these values however based upon the priority selection within the if -> else if 
        //coding these values will not actually print "you have a two pair!" as they will already trigger the "you have 3 of a kind"
        //from the if statement above
        else if (selectOne==selectFour&&selectOne==selectFive||selectOne==selectFour&&selectOne==selectThree||selectOne==selectFour&&selectOne==selectTwo
        ||selectOne==selectFour&&selectTwo==selectThree||selectOne==selectFour&&selectTwo==selectFour||selectOne==selectFour&&selectTwo==selectFive
        ||selectOne==selectFour&&selectThree==selectFive||selectOne==selectFour&&selectFour==selectFive||selectOne==selectFour&&selectThree==selectFour
        
        
        ||selectOne==selectFive&&selectOne==selectThree||selectOne==selectFive&&selectOne==selectTwo
        ||selectOne==selectFive&&selectTwo==selectThree||selectOne==selectFive&&selectTwo==selectFour||selectOne==selectFive&&selectTwo==selectFive
        ||selectOne==selectFive&&selectThree==selectFour||selectOne==selectFive&&selectThree==selectFive||selectOne==selectFive&&selectFour==selectFive
        
        ||selectOne==selectThree&&selectOne==selectTwo||selectOne==selectThree&&selectTwo==selectThree||selectOne==selectThree&&selectTwo==selectFour
        ||selectOne==selectThree&&selectTwo==selectFive||selectOne==selectThree&&selectTwo==selectFive||selectOne==selectThree&&selectThree==selectFour
        ||selectOne==selectThree&&selectThree==selectFive||selectOne==selectThree&&selectFour==selectFive
        
        ||selectOne==selectTwo&&selectTwo==selectThree||selectOne==selectTwo&&selectTwo==selectFour||selectOne==selectTwo&&selectTwo==selectFive
        ||selectOne==selectTwo&&selectThree==selectFour||selectOne==selectTwo&&selectThree==selectFive||selectOne==selectTwo&&selectFour==selectFive
        
        ||selectTwo==selectThree&&selectTwo==selectFour||selectTwo==selectThree&&selectTwo==selectFive||selectTwo==selectThree&&selectThree==selectFour
        ||selectTwo==selectThree&&selectThree==selectFive||selectTwo==selectThree&&selectFour==selectFive
        
        ||selectTwo==selectFour&&selectTwo==selectFive||selectTwo==selectFour&&selectThree==selectFour||selectTwo==selectFour&&selectThree==selectFive
        ||selectTwo==selectFour&&selectFour==selectFive
        
        ||selectTwo==selectFive&&selectThree==selectFour||selectTwo==selectFive&&selectThree==selectFive||selectTwo==selectFive&&selectFour==selectFive
        
        ||selectThree==selectFour&&selectThree==selectFive||selectThree==selectFour&&selectFour==selectFive
        ||selectThree==selectFive&&selectFour==selectFive)
        
        System.out.println("You have a 2 pair!");
        
        //(below) identifying if there is a pair using the same lengthy method as the if and else if statements above
        
        else if (selectOne==selectFour||selectOne==selectFive||selectOne==selectThree||selectOne==selectTwo
        ||selectTwo==selectThree||selectTwo==selectFour||selectTwo==selectFive||selectThree==selectFour
        ||selectThree==selectFive||selectFour==selectFive)
        System.out.println("You have a pair!");
        //(below) else statement to print "you have a high card hand!" if there is not a 3 of a kind, 2 pair, or a pair
        //as there are no other card combination identifiers requested
        else 
        System.out.println("You have a high card hand!");
        
        
    }//end of main method
}//end of class

//doing this without loops was...